version: "3"
services:
  demo:
    image: demo
    ports:
      - "8080:8080"
    networks:
      - acms-mysql
    depends_on:
      - mysqldb
 
  mysqldb:
    image: mysql:8
    networks:
      - acms-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=acms

networks:
  acms-mysql: